- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - awscli
    state: latest
    update_cache: true
- name: Install boto3 and botocore
  pip:
    name: 
      - boto3>=1.26.0
      - botocore>=1.29.0
    state: present
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
- name: Install Docker Module for Python
  pip:
    name: docker
- name: Ensure Docker is started
  service:
    name: docker
    state: started
    enabled: true
- name: Download WAR file from S3
  amazon.aws.s3_object:
    bucket: "{{ s3_bucket }}"
    object: "/artifacts/hello-1.0_{{ custom_date_time }}.war"
    dest: /tmp/hello-1.0.war
    mode: get
    region: "{{ aws_region }}"
- name: Run Tomcat container with the built artifact
  community.docker.docker_container:
    name: tomcat_server
    image: tomcat:9.0.91-jdk8-temurin
    state: started
    recreate: true
    ports:
      - 80:8080
    volumes:
      - /tmp/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war
    restart_policy: always
