log_file_path: "/tmp/ansible_logs/log.txt"  # path for playbook's logfile
aws_region: "eu-north-1"  # AWS region
aws_key_name: "my-key-1"  # AWS key pair name (created or new)
instance_type: "t3.micro"  # AWS EC2 instance type
image_id: "ami-880553530880553530"  # actual AWS AMI ID (check region!)
vpc_id: "vpc-880553530880553530"  # AWS VPC ID
subnet_id: "subnet-880553530880553530" # AWS VPC Subnet ID
s3_bucket: "mys3bucket"  # AWS S3 bucket address (uniq!)
aws_ssh_private_key_file: "~/.ssh/{{ aws_key_name }}.pem"  # path to aws_key_name.pem on host (created or new)
iam_policy_name: "S3AccessPolicy" # Name of AWS IAM policy  with access from EC2 to S3 (new)
iam_role_name: "instance-profile/NAME" # Name of AWS IAM role  with access from EC2 to S3 (created or new)
ec2_security_group_build: "build-sg-01" # AWS EC2 security group (build server)
ec2_security_group_prod: "prod-sg-01" # AWS EC2 security group (prod server)
ec2_inst_name_build: "ec2-build" # AWS EC2 instance / Ansible inventory hostname (builder)
ec2_inst_name_prod: "ec2-prod" # AWS EC2 instance / Ansible inventory hostname (prod)
ec2_inst_env_build: "build-servers" # AWS EC2 instance environment / Ansible inventory group (builder)
ec2_inst_env_prod: "prod-servers" # AWS EC2 instance environment / Ansible inventory group (prod)
