---
- name: Create S3 Bucket and Directories
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../host_vars/all.yml"
  tasks:
    - name: Check if S3 bucket exists
      amazon.aws.s3_bucket_info:
        name: "{{ s3_bucket }}"
        region: "{{ aws_region }}"
      register: s3_bucket_info
#      ignore_errors: false
    - name: Log message if bucket already exists
      debug:
        msg: "S3 bucket {{ s3_bucket }} already exists in {{ aws_region }}. Skipping creation."
      when: s3_bucket_info.buckets is defined and s3_bucket_info.buckets | length > 0
    - name: Log bucket existence in a file
      ansible.builtin.lineinfile:
        path: "{{ log_file_path }}"
        line: "S3 bucket {{ s3_bucket }} already exists in {{ aws_region }}. Skipping creation."
      when: s3_bucket_info.buckets is defined and s3_bucket_info.buckets | length > 0
      
    - name: Create S3 Bucket
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket }}"
        region: "{{ aws_region }}"
        delete_public_access: true
        state: present
      when: s3_bucket_info.buckets is not defined or s3_bucket_info.buckets | length == 0
      register: bucket_creation
    - name: Log message for bucket creation
      debug:
        msg: "S3 bucket {{ s3_bucket }} in {{ aws_region }} created."
      when: bucket_creation.bucket is defined
    - name: Log bucket creation in a file
      ansible.builtin.lineinfile:
        path: "{{ log_file_path }}"
        line: "S3 bucket {{ s3_bucket }} in {{ aws_region }} created."
      when: bucket_creation.bucket is defined
      
    - name: Create directories in the S3 bucket 
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: "{{ item }}/"
        region: "{{ aws_region }}"
        mode: create
      loop:
        - info_aws
        - artifacts
        
    - name: Log message for bucket creation
      debug:
        msg: "Directories 'info_ec2' and 'artifacts' ensured in bucket {{ s3_bucket }}."
    - name: Log directory creation
      ansible.builtin.lineinfile:
        path: "{{ log_file_path }}"
        line: "Directories 'info_aws' and 'artifacts' ensured in bucket {{ s3_bucket }}."
