---
- name: Create S3 Bucket and Directories
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../host_vars/all.yml"
    - "../host_vars/custom_date_time.yml"
  tasks:
    - name: Check if S3 bucket exists
      amazon.aws.s3_bucket_info:
        name: "{{ s3_bucket }}"
        region: "{{ aws_region }}"
      register: s3_bucket_info
#      ignore_errors: false
    - name: Msg message if bucket already exists
      debug:
        msg: "S3 bucket {{ s3_bucket }} already exists in {{ aws_region }}. Skipping creation."
      when: ('s3_setup' in ansible_run_tags) and (s3_bucket_info.buckets is defined and s3_bucket_info.buckets | length > 0)
      tags:
        - msg
        - never
    - name: Log bucket existence in a file
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:S3 bucket {{ s3_bucket }} already exists in {{ aws_region }}. Skipping creation."
      when: ('s3_setup' in ansible_run_tags) and (s3_bucket_info.buckets is defined and s3_bucket_info.buckets | length > 0)
      tags:
        - log
        - never
        
    - name: Create S3 Bucket
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket }}"
        region: "{{ aws_region }}"
        delete_public_access: true
        state: present
      when: s3_bucket_info.buckets is not defined or s3_bucket_info.buckets | length == 0
      register: bucket_creation
    - name: Msg message for bucket creation
      debug:
        msg: "S3 bucket {{ s3_bucket }} in {{ aws_region }} created."
      when: ('s3_setup' in ansible_run_tags) and (bucket_creation.bucket is defined)
      tags:
        - msg
        - never
    - name: Log bucket creation in a file
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:S3 bucket {{ s3_bucket }} in {{ aws_region }} created."
      when: ('s3_setup' in ansible_run_tags) and (bucket_creation.bucket is defined)
      tags:
        - log
        - never
        
    - name: Create directories in the S3 bucket 
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: "{{ item }}/"
        region: "{{ aws_region }}"
        mode: create
      loop:
        - info_aws
        - artifacts
        
    - name: Msg for bucket creation
      debug:
        msg: "Directories 'info_ec2' and 'artifacts' ensured in bucket {{ s3_bucket }}."
      when: 's3_setup' in ansible_run_tags
      tags:
        - msg
        - never
    - name: Log directory creation
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:Directories 'info_aws' and 'artifacts' ensured in bucket {{ s3_bucket }}."
      when: 's3_setup' in ansible_run_tags
      tags:
        - log
        - never
