---
- name: Setup IAM Role and Policy for EC2 Access to S3
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../host_vars/all.yml"
  tasks:
    - name: Check if IAM role exists
      amazon.aws.iam_role_info:
        name: "{{ iam_role_name }}"
        region: "{{ aws_region }}"
      register: iam_role_info
      ignore_errors: true
    
    - name: Create or update IAM Policy for S3 Access
      amazon.aws.iam_managed_policy:
        policy_name: "{{ iam_policy_name }}"
        region: "{{ aws_region }}"
        state: present
        policy_description: S3 Access (GET/PUT/LIST)
        policy: "{{ lookup('template','./files/IAM_policy.json.j2') }}"
      register: s3_access_policy

    - name: Notify if IAM Policy was created or updated
      ansible.builtin.debug:
        msg: "The IAM policy '{{ iam_policy_name }}' was created or updated."
      when: s3_access_policy.changed
    - name: Log if IAM Policy was created or updated
      ansible.builtin.lineinfile:
        path: "{{ log_file_path }}"
        line: "The IAM policy '{{ iam_policy_name }}' was created or updated."
      when: s3_access_policy.changed
      
    - name: Notify if IAM Policy already exists without changes
      ansible.builtin.debug:
        msg: "The IAM policy '{{ iam_policy_name }}' already exists and no updates were needed."
      when: not s3_access_policy.changed
    - name: Log if IAM Policy already exists without changes
      ansible.builtin.lineinfile:
        path: "{{ log_file_path }}"
        line: "The IAM policy '{{ iam_policy_name }}' already exists and no updates were needed."
      when: not s3_access_policy.changed
      
    - name: Create IAM Role for EC2 with S3 Access
      amazon.aws.iam_role:
        name: "{{ iam_role_name }}"
        region: "{{ aws_region }}"
        state: present
        assume_role_policy_document: "{{ lookup('file','./files/IAM_role.json') }}"
        description: Role for EC2 with S3 Access (GET/PUT/LIST)
        managed_policies:
          - "{{ s3_access_policy.policy.arn }}"
      when: iam_role_info.roles is undefined
      
    - name: Notify IAM Role status
      ansible.builtin.debug:
        msg: >
          {% if iam_role_info.roles is undefined %}
            "IAM role '{{ iam_role_name }}' was created."
          {% else %}
            "IAM role '{{ iam_role_name }}' already exists."
          {% endif %}
    - name: Log IAM role status to a block in a file
      ansible.builtin.blockinfile:
        path: "{{ log_file_path }}"
        block: |
          {{ "IAM role '{{ iam_role_name }}' was created."
          if iam_role_info.roles is undefined
          else "IAM role '{{ iam_role_name }}' already exists." }}
