---
- name: Manage EC2 Key Pair for Ansible Access
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../host_vars/all.yml"
    - "../host_vars/custom_date_time.yml"
  tasks:
    # Pre-checks for file and AWS key existence
    - name: Check if AWS key pair exists
      amazon.aws.ec2_key_info:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
      register: aws_key_info
      when: "'key_management' in ansible_run_tags"
      tags:
        - create_key
        - upload_key
    - name: Check if local key file exists
      stat:
        path: "{{ aws_ssh_private_key_file }}"
      register: local_key_file
      when: "'key_management' in ansible_run_tags"
      tags:
        - create_key
        - upload_key
    - name: Log message for key pair and file status
      debug:
        msg: |
          AWS Key Pair exists: {{ aws_key_info.keypairs is defined }}.
          Local key file exists: {{ local_key_file.stat.exists }}.
      when: >
        ("create_key" in ansible_run_tags or "upload_key" in ansible_run_tags)
        and "msg" in ansible_run_tags
        and "key_management" in ansible_run_tags
      tags:
        - msg
        - never
    - name: Log in file for key pair and file status
      blockinfile:
        path: "{{ log_file_path }}"
        block: |
          {{ custom_date_time }}:AWS Key Pair exists: {{ aws_key_info.keypairs is defined }}.
          {{ custom_date_time }}:Local key file exists: {{ local_key_file.stat.exists }}.
      when: >
        ("create_key" in ansible_run_tags or "upload_key" in ansible_run_tags)
        and "log" in ansible_run_tags
        and "key_management" in ansible_run_tags
      tags:
        - log
        - never

    # Create new key if AWS key is missing and local file doesn't exist + tag create_key
    - name: Create new AWS key pair and save locally
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
        state: present
        file_name: "{{ aws_ssh_private_key_file }}"
      when: >
        "key_management" in ansible_run_tags
        and (aws_key_info.keypairs is not defined and not local_key_file.stat.exists)
      tags:
        - create_key
      register: created_key
      notify:
        - Set permissions for SSH key
    - name: Log message for key creation
      debug:
        msg: "New AWS key pair '{{ aws_key_name }}' created and saved locally in {{ aws_ssh_private_key_file }}"
      when: >
        ("key_management" in ansible_run_tags and "create_key" in ansible_run_tags)
        and created_key.changed"
      tags:
        - msg
        - never
    - name: Log in file for key creation
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:New AWS key pair '{{ aws_key_name }}' created and saved locally in {{ aws_ssh_private_key_file }}"
      when: >
        ("key_management" in ansible_run_tags and "create_key" in ansible_run_tags)
        and created_key.changed
      tags:
        - log
        - never
        
    # Upload existing key if local file exists + tag upload_key
    - name: Upload existing local key to AWS
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
        state: present
        key_material: "{{ lookup('file', aws_ssh_private_key_file) }}"
      when: >
        "key_management" in ansible_run_tags
        and (local_key_file.stat.exists and aws_key_info.keypairs is not defined)
#this when state will not go above error when "key already in aws and != aws_ssh_private_key_file" but you can add this (if you dont worry about security problem):
#when: "key_management" in ansible_run_tags and local_key_file.stat.exists and (aws_key_info.keypairs is defined and aws_key_info.keypairs[0].key_fingerprint != lookup('file', aws_ssh_private_key_file) | fingerprint('sha256')
      tags:
        - upload_key
      no_log: true
      notify:
        - Set permissions for SSH key
      register: uploaded_key
    - name: Log message for key creation
      debug:
        msg: "Existing key '{{ aws_key_name }}' uploaded to AWS."
      when: >
        ("key_management" in ansible_run_tags and "upload_key" in ansible_run_tags)
        and uploaded_key.changed
      tags:
        - msg
        - never
    - name: Log in file for key upload
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:Existing key '{{ aws_key_name }}' uploaded to AWS."
      when: >
        ("key_management" in ansible_run_tags and "upload_key" in ansible_run_tags)
        and uploaded_key.changed
      tags:
        - log
        - never

  handlers:
    - name: Set permissions for SSH key
      file:
        path: "{{ aws_ssh_private_key_file }}"
        mode: "0400" # Set permission to read-only for the owner
