---
- name: Manage EC2 Key Pair for Ansible Access
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../host_vars/all.yml"
    - "../host_vars/custom_date_time.yml"
  tasks:
    - name: Check if AWS key pair exists
      amazon.aws.ec2_key_info:
        names: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
      register: aws_key_info
    - name: Check if local key file exists
      stat:
        path: "{{ aws_ssh_private_key_file }}"
      register: local_key_file
    - name: Ensure public key file exists
      stat:
        path: "{{ aws_ssh_private_key_file + '.pub' }}"
      register: public_key_file
      when: >
        "upload_key" in ansible_run_tags and "key_management" in ansible_run_tags

    - name: Log message for key pair and file status
      debug:
        msg: |
          AWS Key Pair {{ aws_key_name }} exists: {{ aws_key_info.keypairs | length > 0 }}.
          Local key file {{ aws_ssh_private_key_file }} exists: {{ local_key_file.stat.exists }}.
      when: >
        ("create_key" in ansible_run_tags or "upload_key" in ansible_run_tags)
        and ("msg" in ansible_run_tags and "key_management" in ansible_run_tags)
      tags:
        - msg
        - never
    - name: Log message for local public key pair
      debug:
        msg: "Public local key file {{ aws_ssh_private_key_file + '.pub' }} exists: {{ public_key_file.stat.exists }}."
      when: >
        "upload_key" in ansible_run_tags and ("msg" in ansible_run_tags and "key_management" in ansible_run_tags)
      tags:
        - msg
        - never        
    - name: Log in file for key pair status
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:AWS Key Pair {{ aws_key_name }} exists: {{ aws_key_info.keypairs | length > 0 }}"
        insertafter: "EOF"
      when: >
        ("create_key" in ansible_run_tags or "upload_key" in ansible_run_tags)
        and ("log" in ansible_run_tags and "key_management" in ansible_run_tags)
      tags:
        - log
        - never
    - name: Log in file for local key file status
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:Local key file {{ aws_ssh_private_key_file }} exists: {{ local_key_file.stat.exists }}"
        insertafter: "EOF"
      when: >
        ("create_key" in ansible_run_tags or "upload_key" in ansible_run_tags)
        and ("log" in ansible_run_tags and "key_management" in ansible_run_tags)
      tags:
        - log
        - never
    - name: Log in file for local public key file status
      lineinfile:
        path: "{{ log_file_path }}"
        line: "{{ custom_date_time }}:Public local key file {{ aws_ssh_private_key_file + '.pub' }} exists: {{ public_key_file.stat.exists }}"
        insertafter: "EOF"
      when: >
        "upload_key" in ansible_run_tags and ("log" in ansible_run_tags and "key_management" in ansible_run_tags)
      tags:
        - log
        - never
        
    # Create new key if AWS key is missing and local file doesn't exist + tag create_key
    - name: Create new AWS key pair and save locally
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
        state: present
        file_name: "{{ aws_ssh_private_key_file }}"
      when: >
        ("key_management" in ansible_run_tags and "create_key" in ansible_run_tags)
        and ((aws_key_info.keypairs | length == 0) and not local_key_file.stat.exists)
      tags:
        - create_key
      register: created_key
      notify:
        - Set permissions for SSH key
    - name: Log message for key creation
      debug:
        msg: >-
          {%- if created_key.changed -%}
            New AWS key pair '{{ aws_key_name }}' created and saved locally in {{ aws_ssh_private_key_file }}
          {%- else -%}
            AWS key pair '{{ aws_key_name }}' already exists and no updates were needed.
          {%- endif -%}
      when: >
        "key_management" in ansible_run_tags and "create_key" in ansible_run_tags and 'msg' in ansible_run_tags
      tags:
        - msg
        - never
    - name: Log in file for key creation
      lineinfile:
        path: "{{ log_file_path }}"
        line: >-
          {%- if created_key.changed -%}
            {{ custom_date_time }}:New AWS key pair '{{ aws_key_name }}' created and saved locally in {{ aws_ssh_private_key_file }}
          {%- else -%}
            {{ custom_date_time }}:AWS key pair '{{ aws_key_name }}' already exists and no updates were needed.
          {%- endif -%}
        insertafter: "EOF"
      when: >
        "key_management" in ansible_run_tags and "create_key" in ansible_run_tags and 'log' in ansible_run_tags
      tags:
        - log
        - never
        
    # Upload existing key if local file exists + tag upload_key
    - name: Upload existing local key to AWS
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
        state: present
        key_material: "{{ lookup('file', aws_ssh_private_key_file + '.pub') }}"
      when: >
        ("key_management" in ansible_run_tags and "upload_key" in ansible_run_tags)
        and ((local_key_file.stat.exists and public_key_file.stat.exists) and (aws_key_info.keypairs | length == 0))
#this when state will not go above error when "key already in aws and != aws_ssh_private_key_file" but you can add this (if you dont worry about security problem):
#when: ("key_management" in ansible_run_tags and "upload_key" in ansible_run_tags) and (local_key_file.stat.exists and public_key_file.stat.exists) and (aws_key_info.keypairs | length > 0 and aws_key_info.keypairs[0].key_fingerprint != lookup('file', aws_ssh_private_key_file) | fingerprint('sha256')
      tags:
        - upload_key
#      no_log: true
      notify:
        - Set permissions for SSH key
      register: uploaded_key
    - name: Log message for key creation
      debug:
        msg: >-
          {%- if uploaded_key.changed -%}
            Existing key '{{ aws_key_name }}' uploaded to AWS
          {%- else -%}
            Existing key '{{ aws_key_name }}' (probably) already exists in AWS and no updates were needed
          {%- endif -%}
      when: >
        "key_management" in ansible_run_tags and "upload_key" in ansible_run_tags and 'msg' in ansible_run_tags
      tags:
        - msg
        - never
    - name: Log in file for key creation
      lineinfile:
        path: "{{ log_file_path }}"
        line: >-
          {%- if uploaded_key.changed -%}
            {{ custom_date_time }}:Existing key '{{ aws_key_name }}' uploaded to AWS
          {%- else -%}
            {{ custom_date_time }}:Existing key '{{ aws_key_name }}' (probably) already exists in AWS and no updates were needed
          {%- endif -%}
        insertafter: "EOF"
      when: >
        "key_management" in ansible_run_tags and "upload_key" in ansible_run_tags and 'log' in ansible_run_tags
      tags:
        - log
        - never

  handlers:
    - name: Set permissions for SSH key
      file:
        path: "{{ aws_ssh_private_key_file }}"
        mode: "0400" # Set permission to read-only for the owner
