---
- name: Manage EC2 Key Pair for Ansible Access
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../host_vars/all.yml"
  tasks:
    - name: Create and save new AWS key pair locally
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
        state: present
        file_name: "{{ aws_ssh_private_key_file }}"  # create and saves private key from AWS locally
      register: keypair
      changed_when: true
      tags:
        - create_key
      
    - name: Upload existing local key to AWS
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
        state: present
        key_material: "{{ lookup('file', 'aws_ssh_private_key_file') }}"  # upload existing key in AWS
      register: keypair
      changed_when: true
      tags::
        - never
        - upload_key

    - name: Set appropriate permissions for the SSH key
      ansible.builtin.file:
        path: "{{ aws_ssh_private_key_file }}"
        mode: "0400"  # Set permission to read-only for the owner
        when: keypair.changed
