- name: Configure Production Server
  hosts: prod-server
  gather_facts: false
  become: true
  roles:
    - deploy
  vars_files:
    - "../host_vars/all.yml"
    - "../host_vars/custom_date_time.yml"
