- name: Stop specified EC2 instance (it will cost!)
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../host_vars/all.yml"
    - "../host_vars/custom_date_time.yml"
  vars:
    ec2_instance_name: ""
    time: "{{ time | default(10) }}"
  tasks:
    - name: Pause for X minutes
      pause:
        minutes: "{{ time }}"
    - name: Retrieve EC2 instances by tag
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ ec2_instance_name }}"
          "instance-state-name": "running"
        region: "{{ aws_region }}"
      register: ec2_instances
    - name: Stop the specified EC2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ item.instance_id }}"
        region: "{{ aws_region }}"
        state: stopped
      loop: "{{ ec2_instances.instances }}"
      when: item.tags.Name == ec2_instance_name
